name: Deploy Angular Web App to Azure Static Web Apps

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["develop"]

env:
  APP_LOCATION: "./" # Location of the Angular client code
  API_LOCATION: "" # Location of the API source code (optional)
  APP_ARTIFACT_LOCATION: "dist/subhan-studio" # Build output directory for Angular
  NODE_VERSION: "20.11.0" # Node.js version to use

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Inject environment variables
      - name: Inject Environment Variables
        run: |
          echo "export const environment = { production: true, apiUrl: '${{ secrets.API_URL }}', azureFunctionKey: '${{ secrets.AZURE_FUNCTION_KEY }}' };" > src/environments/environment.prod.ts

      # Step 5: Build the Angular app
      - name: Build Angular App
        run: npm run build -- --output-path=${{ env.APP_ARTIFACT_LOCATION }} --base-href=/

      # Step 6: Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_CLIFF_0A5511A00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
      env:
        PATH: /opt/hostedtoolcache/node/${{ env.NODE_VERSION }}/x64/bin:${{ env.PATH }}

  close_pull_request_job:
    name: Close Pull Request Job
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    permissions:
      contents: none
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_CLIFF_0A5511A00 }}
          action: "close"
